// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtezrzslsedgjbbrrejs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0ZXpyenNsc2VkZ2piYnJyZWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjA1MTEsImV4cCI6MjA2NzYzNjUxMX0.Ft6DYYQbNg7BqA-azH5g_FK_0tqo9hDX8C_Vg_v_A8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});